# Build stage
FROM node:18-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
COPY public ./public
COPY src ./src
COPY vite.config.js ./vite.config.js
COPY tailwind.config.cjs ./tailwind.config.cjs
RUN npm ci && npm run build

# Production image
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
